project:
  type: website

website:
  description: "A blog built with Quarto"
  title: "Quatro-blog-01-20251006"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

execute:
  freeze: auto


