project:
  type: website

website:
  description: "A blog built with Quarto"
  title: "MedBioInfo Applied Bioinformatics blog by Lara"
  navbar:
    background: white
    right:
        - text: "About"
          href: about.qmd
        - text: "Posts"
          href: posts.qmd
        - icon: github
          href: https://github.com/
        - icon: linkedin
          href: https://www.linkedin.com/in/laralealhernández-bioquímica
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: false
    code-copy: true
    code-overflow: wrap
    code-line-numbers: false
    highlight-style: github
    page-layout: full

execute:
  freeze: auto


